spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss.SSS
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://39.105.169.182:3306/manager?user=root&password=root&useUnicode=true&characterEncoding=utf-8
#    url: jdbc:h2:mem:manager;DB_CLOSE_ON_EXIT=FALSE
  jpa:
    show-sql: true
#    generate-ddl: true
#    hibernate:
#      ddl-auto: create-drop
  activemq:
    broker-url: tcp://39.105.169.182:8086
    user: admin
    password: admin
  jms:
    pub-sub-domain: true
server:
  servlet:
    context-path: /manager
  port: 8081
swagger:
  groupName: manger
  basePackage: com.imooc.manager.controller
logging:
   level:
      com.googlecode.jsonrpc4j: debug
